-- AlterTable
ALTER TABLE "VehicleOwner" ALTER COLUMN "id" DROP DEFAULT,
ALTER COLUMN "first_name" DROP NOT NULL,
ALTER COLUMN "last_name" DROP NOT NULL,
ALTER COLUMN "phone" DROP NOT NULL,
ALTER COLUMN "email" DROP NOT NULL,
ALTER COLUMN "Address" DROP NOT NULL;
DROP SEQUENCE "VehicleOwner_id_seq";

-- AddForeignKey
ALTER TABLE "VehicleOwner" ADD CONSTRAINT "VehicleOwner_id_fkey" FOREIGN KEY ("id") REFERENCES "Webuser"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
